### PR TITLE
Allow trailing comma, PascalCase const and function in inspections

### PR DESCRIPTION
**Pull request by AfzalivE**
Also disallows `_` in Kotlin const to discourage `SCREAMING_SNAKE_CASE`

### CODE REVIEW

**Comment by goncalossilva** [comment]
Hey! Totally unsolicited feedback 😅, but consider not deviating from the baseline established coding style for each platform. I don't know if the first change deviates from Kotlin's (or Android's) recommended style, but the second appears to do so. [Screaming snake case is precisely the recommend style for const, top-level immutable properties, etc](https://kotlinlang.org/docs/coding-conventions.html#property-names). Strictly adhering to established patterns makes everyone's lives easier for a multitude of reasons, such as editor defaults being right by default, avoiding bike shedding around personal preferences, making it easier to contribute to and accept contributions from the wider OSS community, same with onboarding newcomers, etc.

**Review by rastislavvasko — APPROVED** [review]
@AfzalivE Looks good! 👌

@goncalossilva Thanks for the feedback! ❤️

> I don't know if the first change deviates from Kotlin's (or Android's) recommended style

Trailing commas are [optional-but-encouraged in Kotlin](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas). We already require them both at declaration site and call site through detekt! :)

> but the second appears to do so. [Screaming snake case is precisely the recommend style for const, top-level immutable properties, etc](https://kotlinlang.org/docs/coding-conventions.html#property-names).

Indeed, this deviates from the Kotlin conventions. The reason here is internal consistency with Compose code. [Compose guidelines](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#singletons-constants-sealed-class-and-enum-class-values) require (for framework and library devs) PascalCase for constants + singletons + enum values. It actually specifically mentions and links to the Kotlin conventions section. The "Why":

> Jetpack Compose discourages the use and creation of singletons or companion object state that cannot be treated as stable over time and across threads, reducing the usefulness of a distinction between singleton objects and other forms of constants. This forms a consistent expectation of API shape for consuming code whether the implementation detail is a top-level `val`, a `companion object`, an `enum class`, or a `sealed class` with nested `object` subclasses. `myFunction(Foo)` and `myFunction(Foo.Bar)` carry the same meaning and intent for calling code regardless of specific implementation details.

...which I am a fan of! 😄 We discussed it a few times inside the team, last time [here](https://twist.com/a/1585/ch/405759/t/5784221/). Basically, there were increasing inconsistencies in constants naming in Kotlin (non-Compose) code vs our Compose code vs framework Compose code. Arguably, the Compose guideline is a better rule by being simpler and internally consistent! :)

> Strictly adhering to established patterns makes everyone's lives easier for a multitude of reasons, such as editor defaults being right by default, avoiding bike shedding around personal preferences, making it easier to contribute to and accept contributions from the wider OSS community, same with onboarding newcomers, etc.

That's very true! We _could_ make a distinction between public libraries (we don't have any with Compose, IIRC) and private repos, although unsure if it's making things simpler. 🤔

**Comment by goncalossilva** [comment]
Thanks for the context, @rastislavvasko! Afzal also provided it to me via DM. I was unaware, and now it all makes sense. 🙏

> Basically, there were increasing inconsistencies in constants naming in Kotlin (non-Compose) code vs our Compose code vs framework Compose code. 

JetBrains and the different teams inside Google really need to get their heads together, this is a mess. 😅

> That's very true! We could make a distinction between public libraries (we don't have any with Compose, IIRC) and private repos, although unsure if it's making things simpler.

Could it make sense to have Android-specific rules, as that's where compose exists, and Kotlin-specific rules?

Ultimately, I'd love if all of our tech stacks to “just work” with editor + linting (in this case, detekt) defaults. Having said that, I understand that Compose is bringing inconsistencies into the ecosystem that JetBrains/Google have not ironed out and that creates a situation where we should make decisions ourselves.

**Comment by AfzalivE** [comment]
> Ultimately, I'd love if all of our tech stacks to “just work” with editor + linting (in this case, detekt) defaults. Having said that, I understand that Compose is bringing inconsistencies into the ecosystem that JetBrains/Google have not ironed out and that creates a situation where we should make decisions ourselves.

Admittedly, I didn't think about our non-Android Kotlin code. We can introduce a new style `DoistAndroidStyle` and have these changes there perhaps? That way our KMP code can still keep using the non-Compose conventions.

**Comment by rastislavvasko** [comment]
> Could it make sense to have Android-specific rules, as that's where compose exists, and Kotlin-specific rules?

That makes a lot of sense!

**Comment by AfzalivE** [comment]
@rastislavvasko and @goncalossilva, please could you check again?

I realized that the inspection profile which enforced the constant naming was a new file and not used in any existing project, still I've renamed that to `DoistAndroidStyle.xml` so it shouldn't be used in KMM projects. `DoistStyle.xml` for code style has the allow comma format change.

**Review by rastislavvasko — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
